catchTransformer:
  use_mask_head: True
  mask_dim: 256
  mask_feat_level: 0
  mask_embed_layers: 3

PostProcessor:
  num_top_queries: 100
  mask_threshold: 0.5
  score_with_mask: True
  mask_process_chunk: 16

train_dataloader:
  dataset:
    return_masks: True
    transforms:
      ops:
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomZoomOut, fill: 0}
        - {type: RandomIoUCrop, p: 0.8}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [640, 640]}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
      policy:
        name: stop_epoch
        epoch: 72
        ops: ['RandomPhotometricDistort', 'RandomZoomOut', 'RandomIoUCrop']
  collate_fn:
    mixup_prob: 0.0
    copyblend_prob: 0.0
    base_size_repeat: ~

val_dataloader:
  dataset:
    return_masks: False

catchCriterion:
  weight_dict:
    loss_mal: 1
    loss_bbox: 5
    loss_giou: 2
    loss_fgl: 0.15
    loss_ddf: 1.5
    loss_mask: 5
    loss_dice: 5
  losses: ['mal', 'boxes', 'local', 'masks']
  num_mask_points: 4096
  oversample_ratio: 3.0
  importance_sample_ratio: 0.75

  matcher:
    weight_dict:
      cost_class: 2
      cost_bbox: 5
      cost_giou: 2
      cost_mask: 5
      cost_dice: 5
    num_sample_points: 4096

